
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcnn_top.h"

/*
* The configuration table for devices
*/

XCnn_top_Config XCnn_top_ConfigTable[XPAR_XCNN_TOP_NUM_INSTANCES] =
{
	{
		XPAR_CNN_TOP_0_DEVICE_ID,
		XPAR_CNN_TOP_0_S_AXI_CONTROL_BASEADDR
	}
};


